### ISSUE TITLE
Docker issue 

### ISSUE THREAD

**Issue by yyash-patel** [mlpc-ucsd/Uni-3D#4]
Hi !

 when I run the below command - 

docker run -it --gpus all --shm-size 128G -v "$(pwd)":/workspace zx1239856/uni-3d:0.1.0

I get the following error -

bash: /workspace/.bashrc: Permission denied

can you guide me about the what could be the issue?

**Comment by zx1239856** [comment]
It might be because your host UID does not match the one inside docker container, and therefore the privilege is insufficient for the bind mount $(pwd) directory. 

You may want to perform the modification as below. If you use vscode dev containers it will automatically handle this for you. 

https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_change-the-uidgid-of-an-existing-container-user
